/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */

import org.smslib.AGateway;
import org.smslib.IOutboundMessageNotification;
import org.smslib.Library;
import org.smslib.OutboundMessage;
import org.smslib.Service;
import org.smslib.modem.SerialModemGateway;
import gnu.io.*;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.smslib.GatewayException;
import org.smslib.TimeoutException;

public class SMS extends javax.swing.JFrame {
    public static SMS smsApp;

    /**
     * Creates new form SMS
     */
    public SMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDetect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jComboBoxPorts = new javax.swing.JComboBox<>();
        jButtonListPorts = new javax.swing.JButton();
        jButtonSend = new javax.swing.JButton();
        jButtonGetModemInfo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaCellPhoneNo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sms App");

        jButtonDetect.setText("Detect Comm Ports and Devices");
        jButtonDetect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetectActionPerformed(evt);
            }
        });

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setLineWrap(true);
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.setText("This is a sample sms sent from my personal Modem");
        jTextAreaMessage.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaMessage);

        jButtonListPorts.setText("List Ports");
        jButtonListPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListPortsActionPerformed(evt);
            }
        });

        jButtonSend.setText("Send SMS");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jButtonGetModemInfo.setText("Modem Information");
        jButtonGetModemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetModemInfoActionPerformed(evt);
            }
        });

        jTextAreaCellPhoneNo.setColumns(20);
        jTextAreaCellPhoneNo.setLineWrap(true);
        jTextAreaCellPhoneNo.setRows(5);
        jTextAreaCellPhoneNo.setText("+254712345678");
        jScrollPane3.setViewportView(jTextAreaCellPhoneNo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDetect)
                        .addGap(0, 567, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGetModemInfo)
                            .addComponent(jButtonListPorts)
                            .addComponent(jButtonSend))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonDetect)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListPorts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSend)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGetModemInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetectActionPerformed
        new PortsTest().getAndTestCOMPorts();
    }//GEN-LAST:event_jButtonDetectActionPerformed

    private void jButtonListPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListPortsActionPerformed
        	jComboBoxPorts.removeAllItems();

        java.util.Enumeration<CommPortIdentifier> portEnum = CommPortIdentifier.getPortIdentifiers();
        while ( portEnum.hasMoreElements() ) 
        {
            CommPortIdentifier portIdentifier = portEnum.nextElement();
            //System.out.println(portIdentifier.getName()  +  " - " +  getPortTypeName(portIdentifier.getPortType()) );
            jComboBoxPorts.addItem(portIdentifier.getName());
            jTextAreaLog.append("\n" + portIdentifier.getName()  +  " - " +  getPortTypeName(portIdentifier.getPortType()) + "\n");
        }
    }//GEN-LAST:event_jButtonListPortsActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        try{
            sendSMS();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jButtonGetModemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetModemInfoActionPerformed
        try{
            getModemInfo();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonGetModemInfoActionPerformed

    	public void getModemInfo() throws Exception
        {    
                SerialModemGateway gateway = new SerialModemGateway("", jComboBoxPorts.getSelectedItem().toString(), 9600, "", "");

                Service.getInstance().addGateway(gateway);
                Service.getInstance().startService();
                
                jTextAreaLog.append("Modem Information:");
                jTextAreaLog.append("\n  Manufacturer: " + gateway.getManufacturer());
                jTextAreaLog.append("\n  Model: " + gateway.getModel());
                jTextAreaLog.append("\n  Serial No: " + gateway.getSerialNo());
                jTextAreaLog.append("\n  SIM IMSI: " + gateway.getImsi());
                jTextAreaLog.append("\n  Signal Level: " + gateway.getSignalLevel() + " dBm");
                jTextAreaLog.append("\n  Battery Level: " + gateway.getBatteryLevel() + "%");
                
           
                Service.getInstance().stopService();
                Service.getInstance().removeGateway(gateway);

        }
    
        public void sendSMS() throws Exception
        {
                OutboundNotification outboundNotification = new OutboundNotification();

                SerialModemGateway gateway = new SerialModemGateway("", jComboBoxPorts.getSelectedItem().toString(), 9600, "", "");
                gateway.setInbound(true);
                gateway.setOutbound(true);
                //gateway.setSimPin("0000");
                Service.getInstance().setOutboundMessageNotification(outboundNotification);
                Service.getInstance().addGateway(gateway);
                //String status = Service.getInstance().getServiceStatus().toString();
                //if(status=="STARTED"){}
                Service.getInstance().startService();

                String phoneNumbers = jTextAreaCellPhoneNo.getText();
                
                List<String> phoneList = new ArrayList<>(Arrays.asList(phoneNumbers.split(",")));
               
                phoneList.forEach(phoneNumber -> {
                    OutboundMessage msg = new OutboundMessage(phoneNumber, jTextAreaMessage.getText());
                    try {
                        Service.getInstance().sendMessage(msg);
                    } catch (TimeoutException ex) {
                        Logger.getLogger(SMS.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (GatewayException ex) {
                        Logger.getLogger(SMS.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(SMS.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(SMS.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    jTextAreaLog.append(msg.toString());
                });

//                OutboundMessage msg = new OutboundMessage(jTextFieldCellPhoneNo.getText(), jTextAreaMessage.getText());

//                Service.getInstance().sendMessage(msg);
//                
//                
//                
//                jTextAreaLog.append(msg.toString());
           

                Service.getInstance().stopService();
                Service.getInstance().removeGateway(gateway);
        }

        public class OutboundNotification implements IOutboundMessageNotification
        {
                public void process(AGateway gateway, OutboundMessage msg)
                {
                        System.out.println("Outbound handler called from Gateway: " + gateway.getGatewayId());
                        System.out.println(msg);
                }
        }
    
        static String getPortTypeName ( int portType )
    {
        switch ( portType )
        {
            case CommPortIdentifier.PORT_I2C:
                return "I2C";
            case CommPortIdentifier.PORT_PARALLEL:
                return "Parallel";
            case CommPortIdentifier.PORT_RAW:
                return "Raw";
            case CommPortIdentifier.PORT_RS485:
                return "RS485";
            case CommPortIdentifier.PORT_SERIAL:
                return "Serial";
            default:
                return "unknown type";
        }
    }
        
    void appendToJTextAreaLog(String txt)
    {
        jTextAreaLog.append(txt);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                smsApp = new SMS();
                smsApp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetect;
    private javax.swing.JButton jButtonGetModemInfo;
    private javax.swing.JButton jButtonListPorts;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JComboBox<String> jComboBoxPorts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaCellPhoneNo;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextArea jTextAreaMessage;
    // End of variables declaration//GEN-END:variables
}
